../hdl/hazard3_core.v
../hdl/hazard3_cpu_1port.v
////../hdl/hazard3_cpu_2port.v
../hdl/arith/hazard3_alu.v
../hdl/arith/hazard3_branchcmp.v
../hdl/arith/hazard3_mul_fast.v
../hdl/arith/hazard3_muldiv_seq.v
../hdl/arith/hazard3_onehot_encode.v
../hdl/arith/hazard3_onehot_priority.v
../hdl/arith/hazard3_onehot_priority_dynamic.v
../hdl/arith/hazard3_priority_encode.v
../hdl/arith/hazard3_shift_barrel.v
../hdl/hazard3_csr.v
../hdl/hazard3_decode.v
../hdl/hazard3_frontend.v
../hdl/hazard3_instr_decompress.v
../hdl/hazard3_irq_ctrl.v
../hdl/hazard3_pmp.v
../hdl/hazard3_power_ctrl.v
../hdl/hazard3_regfile_1w2r.v
../hdl/hazard3_triggers.v
